### ISSUE TITLE
Duplicate records in S3 ERA5 2023 data

### ISSUE THREAD

**Issue by d-watt** [moptis/era5-for-wrf#1]
Nice work @moptis! Fyi - I'm seeing duplicate records in the S3 ERA5 2023 data. Generated with [tutorials/era5_global_timeseries.ipynb](https://github.com/moptis/era5-for-wrf/blob/main/tutorials/era5_global_timeseries.ipynb), using both default coords and at a couple other locations.

![image](https://github.com/moptis/era5-for-wrf/assets/43971503/d56eafdb-e48f-4fff-bb02-c82a104fb46d)

Also noting `lon` is in 0/360 format, whereas `lat` is -90/90 in `era5-for-wrf/era5_global_gids.csv`. Might be more intuitive to use -180/180 for `lon` instead?

![image](https://github.com/moptis/era5-for-wrf/assets/43971503/f5556637-9ffc-472a-a8de-0667aa6ca55c)

**Comment by moptis** [comment]
@d-watt Thanks for pointing this out! I'll review this weekend and get things fixed up.

**Comment by d-watt** [comment]
@moptis I also noticed that data ends 04/30/2024. Is the S3 data static or being updated automatically? [The CDS API format changed in September](https://confluence.ecmwf.int/display/CKB/Please+read%3A+CDS+and+ADS+migrating+to+new+infrastructure%3A+Common+Data+Store+%28CDS%29+Engine), might've broken an automated update.

**Comment by moptis** [comment]
Hi Devon, good to hear from you. To be honest, I'm not sure I'll keep the ERA5 timeseries data updated. BrightWind's BrightHub seems to be doing a better job of it, anyhow:  https://www.brightwindanalysis.com/home/brighthub/

I'd be curious to learn if you find this data more valuable and why, which may motivate me to keep it going.

Best,

Mike

**Comment by d-watt** [comment]
@moptis no problem, good to discontinue. I typically use an alternate source for ERA5. Was interested in your implementation in S3, but mainly providing feedback in case you intended on persisting the data.
